# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "MemE"
license = "MIT"
licenselink = "https://github.com/reuixiy/hugo-theme-meme/blob/master/LICENSE"
description = "MemE is a powerful and highly customizable GoHugo blog theme."
homepage = "https://github.com/reuixiy/hugo-theme-meme/"
tags = ["Blog", "Minimal", "Clean", "Typography", "Multilingual"]
features = ["Dark Mode", "InstantClick", "KaTeX", "JSON-LD", "Drop Cap", "Service Worker", "TOC"]
min_version = "0.41"

[author]
name = "reuixiy"
homepage = "https://io-oi.me/"
